routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('salary', 'SalaryController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('user','UserController');
    
    Route::group(['prefix' => 'system'], function() {
        Route::resource('department', 'DepartmentController');
        Route::resource('division', 'DivisionController');
        Route::resource('state', 'StateController');
        Route::resource('city', 'CityController');
        Route::resource('country', 'CountryController');
    });
    
    Route::group(['prefix' => 'report'], function() {
        Route::get('employees', 'EmployeeController@report')->name('report.employees');
        Route::get('salaries', 'SalaryController@report')->name('report.salaries');
    });
});

app/Employee.php
<?php

namespace App;

// App

// Laravel
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'firstname',
        'lastname',
        'middlename',
        'address',
        'city_id',
        'state_id',
        'country_id',
        'zip',
        'birthdate',
        'date_hired',
        'department_id',
        'division_id',
        'company_id',
        'picture'
    ];

    protected $dates = ['date_hired', 'birthdate'];
    protected $appends = ['age'];

    // Relations

    public function salary()
    {
        return $this->hasOne(Salary::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function state()
    {
        return $this->belongsTo(State::class);
    }

    public function country()
    {
        return $this->belongsTo(Country::class);
    }

    public function division()
    {
        return $this->belongsTo(Division::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    // Mutators

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getAgeAttribute()
    {
        return Carbon::create()->diffInYears($this->birthdate);
    }
    public function getBdayAttribute()
    {
        return $this->birthdate->format('Y-m-d');
    }

    public function getHiredDateAttribute()
    {
        return $this->date_hired->format('Y-m-d');
    }

    public function getSalaryAmountAttribute()
    {
        return null != $this->salary ? $this->salary->salary : null;
    }
}

app/Salary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Salary extends Model
{
    protected $fillable = ['salary'];

    // Relations
    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'firstname',
        'lastname',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Mutators

    public function getNameAttribute()
    {
        return $this->firstname;
    }
    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }
}

app/Http/Controllers/SalaryController.php
<?php

namespace App\Http\Controllers;

// App
use App\Repositories\EmployeeRepositoryInterface;
use App\Repositories\SalaryRepositoryInterface;
use App\Http\Requests\SalaryRequest;

// Laravel
use Illuminate\Http\Request;

class SalaryController extends Controller
{
    /**
     * Employee Repository implementation 
     */ 
    private $employee;

    /**
     * Salary Repository implementation 
     */ 
    private $salary;

     /**
     * Create new controller instance
     * 
     * @return void 
     */ 
    public function __construct(EmployeeRepositoryInterface $employee, SalaryRepositoryInterface $salary)
    {
        $this->employee = $employee;
        $this->salary = $salary;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $employees = $this->employee->listSearchSalaryResult($request->input('search'))
            ->appends($request->except(['page','_token']));

        $data = [
            'employees' => $employees
        ];
        return view('salaries.index', $data);
    }

    private function saveSalaryForm($request, $employee)
    {
        $data = $request->all();

        // check if employee has already related salary 
        if($employee->salary)
        {
            return $this->salary->update($employee->salary, $data);
        }
        
        return $this->employee->addSalaryToEmployee($employee, $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SalaryRequest $request)
    {
        $employee = $this->employee->findById($request->input('employee_id'));
        $this->saveSalaryForm($request, $employee);

        flash(__('alerts.success'))->success();
        return redirect()->route('salary.show', $employee->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Salary  $salary
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $employee = $this->employee->findById($id);

        $data = [
            'employee' => $employee,
            'salary' => $employee->salary
        ];
        return view('salaries.edit_create', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Salary  $salary
     * @return \Illuminate\Http\Response
     */
    public function update(SalaryRequest $request, $id)
    {
        $salary = $this->salary->findById($id);
        $this->salary->update($salary, $request->all());

        flash(__('alerts.success'))->success();
        return redirect()->route('salary.show', $salary->employee_id);
    }

    public function report()
    {
        $employees = $this->employee->getAllEmployeeSalaryReport();
            
        $data = [
            'employees' => $employees
        ];
        return view('salaries.report', $data);
    }
}

resources/views/salaries/edit_create.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('salary.index') }}">Back to List</a>
    <h1>Salary {{ isset($employee) ? '- ' . $employee->fullname : '' }}</h1>

    <div class="row">
        <div class="col-lg-6">
            
            @include('partials.alerts')

            <form action="{{ isset($salary) ? route('salary.update', $salary->id) : route('salary.store') }}" method="POST">
                @csrf
                @method(isset($salary) ? 'PUT' : 'POST')

                <input type="hidden" name="employee_id" value="{{ $employee->id }}">
        
                <div class="form-group">
                    <label for="">Salary Amount</label>
                    <input type="text" name="salary" value="{{ old('salary', (isset($salary) ? $salary->salary : '' )) }}" class="form-control">
                </div>

        
        
                <button class="btn btn-primary btn-block" role="submit">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/salaries/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Salaries</h1>

    @include('partials.alerts')

    <form>
        <div class="input-group mb-2">
            <input type="text" name="search" placeholder="Search by employee name, department and salary." class="form-control" value="{{ Request::input('search') }}">
            <div class="input-group-append">
                <button class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
            <th>ID</th>
            <th>Employee</th>
            <th>Department</th>
            <th>Salary</th>
            <th></th>
        </thead>
        @if($employees)
            @foreach($employees as $employee)
                <tr>
                    <td>{{ $employee->id }}</td>
                    <td>{{ $employee->fullname }}</td>
                    <td>{{ $employee->department->name }}</td>
                    <td>{{ $employee->salary_amount }}</td>
                    <td class="text-center">
                        <a href="{{ route('salary.show', $employee->id) }}">Edit</a>
                    </td>
                </tr>
            @endforeach
        @endif
    </table>

    {{ $employees->links() }}
@endsection

resources/views/salaries/report.blade.php
@extends('layouts.app')

@section('content')
    <h1>Reports - Salaries</h1>
    <div class="mb-3 d-block">
        <a class="" href="{{ route('report.salaries') }}">Salaries</a> | <a class="" href="{{ route('report.employees') }}">Reports</a>
    </div>

    @include('partials.alerts')

    <div id="customers">
        <table class="table table-borderless">
            <colgroup>
                <col width="10%">
                <col width="45%">
                <col width="45%">
            </colgroup>
            <thead>
                <th>ID</th>
                <th>Employee</th>
                <th>Salary</th>
            </thead>
            @if($employees)
                @foreach($employees as $employee)
                    <tr>
                        <td>{{ $employee->id }}</td>
                        <td>{{ $employee->fullname }}</td>
                        <td>{{ $employee->salary_amount }}</td>
                    </tr>
                @endforeach
            @endif
        </table>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
@endpush

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js" ></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js" ></script>
    
    <script>
        $(function() {
            $(document).ready(function() {
                $('#customers table').DataTable( {
                    dom: 'Bfrtip',
                    searching: false,
                    ordering: false,
                    info: false,
                    paging: false,
                    buttons: [
                        'excelHtml5',
                        'pdfHtml5'
                    ]
                } );
            } );
        });
    </script>
@endpush