routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('salary', 'SalaryController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('user','UserController');
    
    Route::group(['prefix' => 'system'], function() {
        Route::resource('department', 'DepartmentController');
        Route::resource('division', 'DivisionController');
        Route::resource('state', 'StateController');
        Route::resource('city', 'CityController');
        Route::resource('country', 'CountryController');
    });
    
    Route::group(['prefix' => 'report'], function() {
        Route::get('employees', 'EmployeeController@report')->name('report.employees');
        Route::get('salaries', 'SalaryController@report')->name('report.salaries');
    });
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class City extends Model
{
    protected $fillable = [
        'name',
        'state_id'
    ];

    protected $with = ['state'];
    
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('state_id', function (Builder $builder) {
            $builder->whereNotNull('state_id');
            $builder->orderBy('name', 'ASC');
        });
    }

    // Relations
    public function state()
    {
        return $this->belongsTo(State::class);
    }

    
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

// App
use App\Repositories\CityRepositoryInterface;
use App\Repositories\StateRepositoryInterface;
use App\Repositories\CountryRepositoryInterface;


use App\Http\Requests\CityRequest;

// laravel
use Illuminate\Http\Request;

class CityController extends Controller
{

    /**
     * City Repository implementation 
     */ 
    private $city;

    /**
     * State Repository implementation 
     */ 
    private $state;

    /**
     * Country Repository implementation 
     */ 
    private $country;

    /**
     * Create new instance of controller
     * 
     * @return void
     */
    public function __construct(
        CityRepositoryInterface $city,
        StateRepositoryInterface $state,
        CountryRepositoryInterface $country
        )
    {
        $this->city = $city;
        $this->state = $state;
        $this->country = $country;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $cities = $this->city->listSearchResult($request->input('search'))
            ->appends($request->except(['page','_token']));
        $data = [
            'cities' => $cities
        ];
        return view('cities.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->showCityForm();
    }

    /**
     * Return the Edit or Create city page
     */ 
    public function showCityForm($city = null)
    {
        $countries = $this->country->getCountryWithStates();
        $states = $this->state->getAll();

        $data = [
            'countries' => $countries,
            'states' => $states
        ];

        if($city) {
            $data['city'] = $city;
        }

        return view('cities.edit_create', $data);
    }

    /**
     * Save or Update an Employee
     * 
     * @return mixed
     */ 
    private function saveCityForm($request, $city = null)
    {
        $data = $request->all();

        if($city) {
            return $this->city->update($city, $data);
        }
        
        return $this->city->create($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CityRequest $request)
    {
        $city = $this->saveCityForm($request);

        flash(__('alerts.success'))->success();
        return redirect()->route('city.show', $city->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $city = $this->city->findById($id);
        return $this->showCityForm($city);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(CityRequest $request, $id)
    {
        $city = $this->city->findById($id);
        $this->saveCityForm($request, $city);

        flash(__('alerts.success'))->success();
        return redirect()->route('city.show', $city->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->city->delete($id);

        flash(__('alerts.success'))->success();
        return redirect()->route('city.index');
    }
}

resources/views/cities/edit_create.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('city.index') }}">Back to Cities</a>
    <h1>{{ isset($city) ? 'Edit' : 'Create' }} City</h1>

    <div class="row">
        <div class="col-lg-6">
            
            @include('partials.alerts')

            <form action="{{ isset($city) ? route('city.update', $city->id) : route('city.store') }}" method="POST">
                @csrf
                @method(isset($city) ? 'PUT' : 'POST')
        
                <div class="form-group">
                    <label for="">City Name</label>
                    <input type="text" name="name" value="{{ old('name', (isset($city) ? $city->name : '' )) }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Country</label>
                    <select name="country_id" class="form-control">
                        <option value="">Select Country</option>

                        @foreach($countries as $country)
                            <option 
                                value="{{ $country->id }}"
                                @if(old('country_id'))
                                    {{ old('country_id') == $country->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($city) ? ( $city->state->country_id == $country->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $country->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="">State</label>
                    <select name="state_id" class="form-control">
                        <option value="">Select State</option>

                        @foreach($states as $state)
                            <option 
                                value="{{ $state->id }}"
                                data-country-id="{{ $state->country_id }}"
                                @if(old('state_id'))
                                    {{ old('state_id') == $state->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($city) ? ( $city->state_id == $state->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $state->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
        
        
                <button class="btn btn-primary btn-block" role="submit">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/cities/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Cities</h1>
    <a class="mb-3 d-block" href="{{ route('city.create') }}">Add</a>
    
    @include('partials.alerts')

    <form>
        <div class="input-group mb-2">
            <input type="text" name="search" placeholder="Search city name" class="form-control" value="{{ Request::input('search') }}">
            <div class="input-group-append">
                <button class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>State</th>
            <th>Country</th>
            <th></th>
        </thead>
        @if($cities)
            @foreach($cities as $city)
                <tr>
                    <td>{{ $city->id }}</td>
                    <td>{{ $city->name }}</td>
                    <td>{{ $city->state ? $city->state->name : '' }}</td>
                    <td>{{ $city->state ? ($city->state->country ? $city->state->country->name : '' ) : '' }}</td>
                    <td class="text-center">
                        <a href="{{ route('city.show', $city->id) }}">Edit</a>
                        <form action="{{ route('city.destroy', $city->id) }}" method="POST" class="d-inline action-delete">
                            @csrf
                            @method('DELETE')
                            <button href="#" role="submit" class="text-danger btn btn-link">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endif
    </table>

    {{ $cities->links() }}
@endsection