routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('salary', 'SalaryController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('user','UserController');
    
    Route::group(['prefix' => 'system'], function() {
        Route::resource('department', 'DepartmentController');
        Route::resource('division', 'DivisionController');
        Route::resource('state', 'StateController');
        Route::resource('city', 'CityController');
        Route::resource('country', 'CountryController');
    });
    
    Route::group(['prefix' => 'report'], function() {
        Route::get('employees', 'EmployeeController@report')->name('report.employees');
        Route::get('salaries', 'SalaryController@report')->name('report.salaries');
    });
});

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class State extends Model
{
    protected $fillable = ['name', 'country_id'];
    protected $with = ['country'];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('country_id', function (Builder $builder) {
            $builder->whereNotNull('country_id');
            $builder->orderBy('name', 'ASC');
        });
    }
    

    // Relations

    public function country()
    {
        return $this->belongsTo(Country::class);
    }

    public function cities()
    {
        return $this->hasMany(City::class);
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

// App
use App\Repositories\StateRepositoryInterface;
use App\Repositories\CountryRepositoryInterface;

use App\Http\Requests\StateRequest;

// Laravel
use Illuminate\Http\Request;

class StateController extends Controller
{
    /**
     * State Repository implementation 
     */ 
    private $state;

    /**
     * Country Repository implementation 
     */ 
    private $country;

    /**
     * Create new controller instance
     * 
     * @return void 
     */ 
    public function __construct(StateRepositoryInterface $state, CountryRepositoryInterface $country)
    {
        $this->state = $state;
        $this->country = $country;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $states = $this->state->listAllPaginated()
            ->appends($request->except(['page','_token']));
        $data = [
            'states' => $states
        ];
        return view('states.index', $data);
    }

    private function showStateForm($state = null)
    {
        $countries = $this->country->getAll();

        $data = [
            'countries' => $countries
        ];

        if($state) {
            $data['state'] = $state;
        }
        return view('states.edit_create', $data);
    }

    private function saveStateForm($request, $state = null)
    {
        $data = $request->all();

        if($state) {
            return $this->state->update($state, $data);
        }

        return $this->state->create($data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->showStateForm();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StateRequest $request)
    {
        $state = $this->saveStateForm($request);

        flash(__('alerts.success'))->success();
        return redirect()->route('state.show', $state->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $state = $this->state->findById($id);
        return $this->showStateForm($state);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function update(StateRequest $request, $id)
    {
        $state = $this->state->findById($id);
        $this->saveStateForm($request, $state);

        flash(__('alerts.success'))->success();
        return redirect()->route('state.show', $state->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->state->delete($id);

        flash(__('alerts.success'))->success();
        return redirect()->route('state.index');
    }
}

resources/views/states/edit_create.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('state.index') }}">Back to States</a>
    <h1>{{ isset($state) ? 'Edit' : 'Create' }} State</h1>

    <div class="row">
        <div class="col-lg-6">
            
            @include('partials.alerts')

            <form action="{{ isset($state) ? route('state.update', $state->id) : route('state.store') }}" method="POST">
                @csrf
                @method(isset($state) ? 'PUT' : 'POST')
        
                <div class="form-group">
                    <label for="">State Name</label>
                    <input type="text" name="name" value="{{ old('name', (isset($state) ? $state->name : '' )) }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Country</label>
                    <select name="country_id" class="form-control">
                        <option value="">Select Country</option>

                        @foreach($countries as $country)
                            <option 
                                value="{{ $country->id }}"
                                @if(old('country_id'))
                                    {{ old('country_id') == $country->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($state) ? ( $state->country_id == $country->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $country->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
        
        
                <button class="btn btn-primary btn-block" role="submit">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/states/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>States</h1>
    <a class="mb-3 d-block" href="{{ route('state.create') }}">Add</a>
    
    @include('partials.alerts')

    <table class="table table-bordered">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Country</th>
            <th></th>
        </thead>
        @if($states)
            @foreach($states as $state)
                <tr>
                    <td>{{ $state->id }}</td>
                    <td>{{ $state->name }}</td>
                    <td>{{ $state->country->name }}</td>
                    <td class="text-center">
                        <a href="{{ route('state.show', $state->id) }}">Edit</a>
                        <form action="{{ route('state.destroy', $state->id) }}" method="POST" class="d-inline action-delete">
                            @csrf
                            @method('DELETE')
                            <button href="#" role="submit" class="text-danger btn btn-link">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endif
    </table>

    {{ $states->links() }}
@endsection