routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('salary', 'SalaryController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('user','UserController');
    
    Route::group(['prefix' => 'system'], function() {
        Route::resource('department', 'DepartmentController');
        Route::resource('division', 'DivisionController');
        Route::resource('state', 'StateController');
        Route::resource('city', 'CityController');
        Route::resource('country', 'CountryController');
    });
    
    Route::group(['prefix' => 'report'], function() {
        Route::get('employees', 'EmployeeController@report')->name('report.employees');
        Route::get('salaries', 'SalaryController@report')->name('report.salaries');
    });
});

app/Employee.php
<?php

namespace App;

// App

// Laravel
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'firstname',
        'lastname',
        'middlename',
        'address',
        'city_id',
        'state_id',
        'country_id',
        'zip',
        'birthdate',
        'date_hired',
        'department_id',
        'division_id',
        'company_id',
        'picture'
    ];

    protected $dates = ['date_hired', 'birthdate'];
    protected $appends = ['age'];

    // Relations

    public function salary()
    {
        return $this->hasOne(Salary::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function state()
    {
        return $this->belongsTo(State::class);
    }

    public function country()
    {
        return $this->belongsTo(Country::class);
    }

    public function division()
    {
        return $this->belongsTo(Division::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    // Mutators

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getAgeAttribute()
    {
        return Carbon::create()->diffInYears($this->birthdate);
    }
    public function getBdayAttribute()
    {
        return $this->birthdate->format('Y-m-d');
    }

    public function getHiredDateAttribute()
    {
        return $this->date_hired->format('Y-m-d');
    }

    public function getSalaryAmountAttribute()
    {
        return null != $this->salary ? $this->salary->salary : null;
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

// App
use App\Employee;

use App\Repositories\EmployeeRepositoryInterface;
use App\Repositories\CountryRepositoryInterface;
use App\Repositories\CityRepositoryInterface;
use App\Repositories\StateRepositoryInterface;
use App\Repositories\DivisionRepositoryInterface;
use App\Repositories\DepartmentRepositoryInterface;
use App\Repositories\CompanyRepositoryInterface;

use App\Http\Requests\EmployeeRequest;

// Laravel
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Employee Repository implementation 
     */ 
    private $employee;

    /**
     * Country Repository implementation 
     */ 
    private $country;

    /**
     * City Repository implementation 
     */ 
    private $city;

    /**
     * State Repository implementation 
     */ 
    private $state;

    /**
     * Division Repository implementation 
     */ 
    private $division;

    /**
     * Department Repository implementation 
     */ 
    private $department;

    /**
     * Department Repository implementation 
     */ 
    private $company;

    /**
     * Create new controller instance
     * 
     * @return void 
     */ 
    public function __construct(
        EmployeeRepositoryInterface $employee,
        CountryRepositoryInterface $country,
        CityRepositoryInterface $city,
        StateRepositoryInterface $state,
        DivisionRepositoryInterface $division,
        DepartmentRepositoryInterface $department,
        CompanyRepositoryInterface $company
    )
    {
        $this->employee = $employee;
        $this->country = $country;
        $this->city = $city;
        $this->state = $state;
        $this->division = $division;
        $this->department = $department;
        $this->company = $company;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $employees = $this->employee->listSearchResult($request->input('search'))
            ->appends($request->except(['page','_token']));
        
        $data = [
            'employees' => $employees
        ];
        return view('employees.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->showEmployeeForm();
    }
    
    /**
     * Return the Edit or Create employee page
     */ 
    public function showEmployeeForm($employee = null)
    {
        $cities = $this->city->getAll();
        $states = $this->state->getAll();
        $countries = $this->country->getCountryWithCities();
        $divisions = $this->division->getAll();
        $departments = $this->department->getAll();
        $companies = $this->company->getAll();

        $data = [
            'cities'        => $cities,
            'states'        => $states,
            'countries'     => $countries,
            'divisions'     => $divisions,
            'departments'   => $departments,
            'companies'     => $companies,
        ];

        if($employee) {
            $data['employee'] = $employee;
        }

        return view('employees.edit_create', $data);
    }

    /**
     * Save or Update an Employee
     * 
     * @return mixed
     */ 
    public function saveEmployeeForm($request, $employee = null)
    {
        $data = $request->except(['_token', 'picture']);

        // If uploaded an image
        if($request->hasFile('picture')) {
            // Generate filename
            $getimageName = time().'.'.$request->picture->getClientOriginalExtension();
            // Upload
            $request->picture->move(public_path('uploads'), $getimageName);
            
            $data['picture'] = $getimageName;
        }

        if($employee) {
            return $this->employee->update($employee, $data);
        }
        
        return $this->employee->create($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        // Save the employee
        $employee = $this->saveEmployeeForm($request);

        flash(__('alerts.success'))->success();
        return redirect()->route('employee.show', $employee->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = $this->employee->findById($id);
        return $this->showEmployeeForm($employee);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        $employee = $this->employee->findById($id);
        $this->saveEmployeeForm($request, $employee);

        flash(__('alerts.success'))->success();
        return redirect()->route('employee.show', $employee->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = $this->employee->findById($id);

        $this->employee->delete($id);

        flash(__('alerts.success'))->success();
        return redirect()->route('employee.index');
    }

    public function report(Request $request)
    {
        // @TODO
        $employees = $this->employee->getEmployeeReport($request);

        $data = [
            'employees' => $employees
        ];
        return view('employees.report', $data);
    }
}

resources/views/employees/edit_create.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('employee.index') }}">Back to Employees</a>
    <h1>{{ isset($employee) ? 'Edit' : 'Create' }} Employee</h1>

    <div class="row">
        <div class="col-lg-6">
            @include('partials.alerts')

    
            <form action="{{ isset($employee) ? route('employee.update', $employee->id) : route('employee.store') }}" method="POST"  enctype="multipart/form-data">
                @csrf
                @method(isset($employee) ? 'PUT' : 'POST')
                
                <h4>Basic Info</h4>
                <div class="form-group">
                    <label for="">Firstname</label>
                    <input type="text" name="firstname" value="{{ old('firstname', (isset($employee) ? $employee->firstname : '' )) }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">Middlename</label>
                    <input type="text" name="middlename" value="{{ old('middlename', (isset($employee) ? $employee->middlename : '' )) }}" class="form-control">
                </div>
        
                <div class="form-group">
                    <label for="">Lastname</label>
                    <input type="text" name="lastname" value="{{ old('lastname', (isset($employee) ? $employee->lastname : '' )) }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Date of Birth</label>
                    <input type="text" name="birthdate" value="{{ old('birthdate', (isset($employee) ? $employee->bday : '' )) }}" class="form-control datepicker"  autocomplete="off">
                </div>
                @if(isset($employee))
                    <div class="form-group">
                        <label for="">Age</label>
                        <input type="text" readonly value="{{ $employee->age }}" class="form-control">
                    </div>
                @endif
                <div class="form-group">
                    <label for="">Photo</label>
                    @if(isset($employee))
                        <img class="img-fluid picture-preview" src="{{ $employee->picture ? asset('uploads/' . $employee->picture) : 'https://www.chaarat.com/wp-content/uploads/2017/08/placeholder-user.png' }}">
                    @else
                        <img class="img-fluid picture-preview" src="https://www.chaarat.com/wp-content/uploads/2017/08/placeholder-user.png">
                    @endif
                    <input type="file" name="picture" value="{{ old('picture', (isset($employee) ? $employee->picture : '' )) }}" class="form-control">
                </div>

                <h4>Address</h4>

                <div class="form-group">
                    <label for="">Address</label>
                    <input type="text" name="address" value="{{ old('address', (isset($employee) ? $employee->address : '' )) }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Country</label>
                    <select name="country_id" class="form-control">
                        <option value="">Select Country</option>

                        @foreach($countries as $country)
                            <option 
                                value="{{ $country->id }}"
                                @if(old('country_id'))
                                    {{ old('country_id') == $country->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->country_id == $country->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $country->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="">State</label>
                    <select name="state_id" class="form-control">
                        <option value="">Select State</option>

                        @foreach($states as $state)
                            <option
                                value="{{ $state->id }}"
                                data-country-id="{{ $state->country_id }}"
                                @if(old('state_id'))
                                    {{ old('state_id') == $state->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->state_id == $state->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $state->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="">City</label>
                    <select name="city_id" class="form-control">
                        <option value="">Select City</option>

                        @foreach($cities as $city)
                            <option
                                value="{{ $city->id }}"
                                data-state-id="{{ $city->state_id }}"
                                data-country-id="{{ $city->state->country->id }}"
                                @if(old('city_id'))
                                    {{ old('city_id') == $city->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->city_id == $city->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                    {{ $city->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                

                <div class="form-group">
                    <label for="">ZIP</label>
                        <input type="text" name="zip" value="{{ old('zip', (isset($employee) ? $employee->zip : '' )) }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">Department</label>
                    <select name="department_id" class="form-control">
                        <option value="">Select Department</option>

                        @foreach($departments as $department)
                            <option 
                                value="{{ $department->id }}"
                                @if(old('department_id'))
                                    {{ old('department_id') == $department->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->department_id == $department->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $department->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="">Division</label>
                    <select name="division_id" class="form-control">
                        <option value="">Select division</option>

                        @foreach($divisions as $division)
                            <option 
                                value="{{ $division->id }}"
                                @if(old('division_id'))
                                    {{ old('division_id') == $division->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->division_id == $division->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $division->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Company</label>
                    <select name="company_id" class="form-control">
                        <option value="">Select company</option>

                        @foreach($companies as $company)
                            <option 
                                value="{{ $company->id }}"
                                @if(old('company_id'))
                                    {{ old('company_id') == $company->id ? ' selected="selected"' : '' }}
                                @else
                                    {{ isset($employee) ? ( $employee->company_id == $company->id ? ' selected="selected"' : ''  ) : '' }}
                                @endif
                            >
                                {{ $company->name }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="">Date Hired</label>
                    <input type="text" name="date_hired" value="{{ old('date_hired', (isset($employee) ? $employee->hired_date : '' )) }}" class="form-control datepicker" autocomplete="off">
                </div>


        
                <button class="btn btn-primary btn-block" role="submit">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Employees</h1>
    <div class="mb-3 d-block">
        <a class="" href="{{ route('employee.create') }}">Add</a> | <a class="" href="{{ route('salary.index') }}">Salaries</a> | <a class="" href="{{ route('report.employees') }}">Reports</a>
    </div>

    @include('partials.alerts')

    <form>
        <div class="input-group mb-2">
            <input type="text" name="search" placeholder="Search employee by name and department." class="form-control" value="{{ Request::input('search') }}">
            <div class="input-group-append">
                <button class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Department</th>
            <th>Company</th>
            <th>Location</th>
            <th>Date Hired</th>
            <th></th>
        </thead>
        @if($employees)
            @foreach($employees as $employee)
                <tr>
                    <td>{{ $employee->id }}</td>
                    <td>{{ $employee->fullname }}</td>
                    <td>{{ $employee->department->name }}</td>
                    <td>{{ $employee->company->name }}</td>
                    <td>{{ $employee->state ? $employee->state->name . ', ' : '' }}{{ $employee->country ? $employee->country->name : '' }}</td>
                    <td>{{ $employee->hired_date }}</td>
                    <td class="text-center">
                        <a href="{{ route('employee.show', $employee->id) }}">Edit</a>
                        <form action="{{ route('employee.destroy', $employee->id) }}" method="POST" class="d-inline action-delete">
                            @csrf
                            @method('DELETE')
                            <button href="#" role="submit" class="text-danger btn btn-link">Delete</button>
                        </form>

                    </td>
                </tr>
            @endforeach
        @endif
    </table>

    {{ $employees->links() }}
@endsection

resources/views/employees/report.blade.php
@extends('layouts.app')

@section('content')
    <h1>Reports - Employees</h1>
    <div class="mb-3 d-block">
        <a class="" href="{{ route('report.salaries') }}">Salaries</a> | <a class="" href="{{ route('report.employees') }}">Reports</a>
    </div>

    @include('partials.alerts')

    <form>
        <div class="input-group mb-2">
            <input type="text" name="date_start" value="{{ Request::input('date_start') }}" class="form-control datepicker" autocomplete="off">
            <input type="text" name="date_end" value="{{ Request::input('date_end') }}" class="form-control datepicker"  autocomplete="off">
            <div class="input-group-append">
                <button class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <div id="customers">
        <table class="table table-borderless">
            <colgroup>
                <col width="5%">
                <col width="20%">
                <col width="20%">
                <col width="20%">
                <col width="20%">
                <col width="15%">
            </colgroup>
            <thead>
                <th>ID</th>
                <th>Name</th>
                <th>Department</th>
                <th>Company</th>
                <th>Location</th>
                <th>Date Hired</th>
            </thead>
            @if($employees)
                @foreach($employees as $employee)
                    <tr>
                        <td>{{ $employee->id }}</td>
                        <td>{{ $employee->fullname }}</td>
                        <td>{{ $employee->department->name }}</td>
                        <td>{{ $employee->company->name }}</td>
                        <td>{{ $employee->state ? $employee->state->name . ',' : '' }} {{ $employee->country ? $employee->country->name : '' }}</td>
                        <td>{{ $employee->hired_date }}</td>
                    </tr>
                @endforeach
            @endif
        </table>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
@endpush

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js" ></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js" ></script>
    
    <script>
        $(function() {
            $(document).ready(function() {
                $('#customers table').DataTable( {
                    dom: 'Bfrtip',
                    searching: false,
                    buttons: [
                        'excelHtml5',
                        'pdfHtml5'
                    ]
                } );
            } );
        });
    </script>
@endpush